companieshouse/acsp-manage-users-api

- src/main/java/uk/gov/companieshouse/acsp/manage/users/configuration/InterceptorConfig.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/interceptor/AuthorizationInterceptor.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/interceptor/AuthorizationInterceptorTest.java
Added Eric interceptors
IDVA6-1148
> Added interceptors

- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/AcspDataDao.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/AcspMembersDao.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/repositories/AcspDataRepository.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/repositories/AcspMembersRepository.java
> Added data layer

- terraform/groups/ecs-service/locals.tf
- terraform/groups/ecs-service/variables.tf
> Chaning variables

- terraform/groups/ecs-service/locals.tf
> listener path changes

- pom.xml
- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipListForAcsp.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/UserAcspMembership.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/UserAcspMembershipInternal.java
- Small PR, adding concrete implementation of the rest endpoints
- Relevant TODO comments corresponding to the JIRAs
- Should hopefully reduce conflicts once we're working on these in parallel
> ACSP: Add concrete controllers with relevant TODOs

- src/main/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembersMapper.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembershipListMapper.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembershipMapper.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/mapper/BaseMapper.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/AcspDataService.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/utils/MapperUtil.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/common/DateUtils.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/common/TestDataManager.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembersMapperTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembershipListMapperTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembershipMapperTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/mapper/BaseMapperTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/utils/MapperUtilTest.java
Added all of the mappers. This should unblock: 
- GET /acsp-members/acsps/{acsp_number}
- GET /acsp-members
- GET /acsp-members/{id}
IDVA6-1142
> Idva6 1142 add mappers

- pom.xml
- src/main/resources/application.properties
Had guessed the image url's before they were created. Checked, them and they are correct. Removed comments.
IDVA6-1225
> Checked that the images are correct.

- src/main/java/uk/gov/companieshouse/acsp/manage/users/configuration/InterceptorConfig.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/UserAcspMembership.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/AcspMembersDao.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/repositories/AcspMembersRepository.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersService.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/UserAcspMembershipTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembersServiceIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/UserAcspMembershipIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/model/AcspMembersDaoTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersServiceTest.java
- src/test/resources/application.properties
- Implemented `GET /acsp-members/` 
- Add test for the relevant endpoint method
- Follows LLD here:
- https://companieshouse.atlassian.net/wiki/spaces/IDV/pages/4708106297/LLD+-+GET+acsp-members
https://companieshouse.atlassian.net/browse/IDVA6-1145
> IDVA6-1145: Acsp membership for logged in user

- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/UserAcspMembership.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/UserAcspMembershipInternal.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/UserAcspMembershipInternalTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembersMapperTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembershipListMapperTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/mapper/BaseMapperTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/utils/MapperUtilTest.java
- Replace public test classes with package-private (default) visibility
- Use explicit scoping instead of the default package-private
- Remove unused constants and imports
- Improve test structure and readability in mapper tests
- Add null checks and use Objects.requireNonNull()
- Remove empty constructor or add explanatory comment
- Use 'final' for variables where appropriate
- Simplify test methods by extracting common setup into helper methods
Sonar code smells addressed:
- Classes should be defined in named packages
- Utility classes should not have public constructors
- Unused private fields should be removed
- Tests should include assertions
- "public" classes and methods should be documented
- Variables should not be self-assigned
__An exhaustive list of peer review checks can be …
> BAU: Fix code smells and improve test coverage

- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/UserAcspMembershipInternal.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/repositories/AcspMembersRepository.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersService.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/UserAcspMembershipInternalTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersServiceTest.java
Changes:
- Controller and service methods for POST request created
- Unit tests added
https://companieshouse.atlassian.net/browse/IDVA6-1238
> IDVA6-1238 acsp manage users api internal post

- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/UserAcspMembership.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembershipService.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/UserAcspMembershipTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/UserAcspMembershipIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembershipServiceTest.java
GET /acsp-members/{id}
idva6-1146
* [ x] I have added unit tests for new code that I have added
* [ x] I have added/updated functional tests where appropriate
* [ x] The code follows our [coding standards](https://github.com/companieshouse/styleguides/blob/master/java.md)
> idva6-1146  Get endpoint

- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/UserAcspMembership.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/repositories/AcspMembersRepository.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersService.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/common/TestDataManager.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/UserAcspMembershipTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembersRepositoryTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembersServiceTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/UserAcspMembershipIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersServiceTest.java
Added PATCH /acsp-members/{id}
IDVA6-1147
> Idva6 1147 update and role and remove

- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/UserAcspMembershipInternal.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/AcspMembersDao.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/UserAcspMembershipInternalTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/UserAcspMembershipInternalIntegrationTest.java
- Add isActiveMember method in UserAcspMembershipInternal controller
- Implement fetchActiveAcspMemberByUserIdAndAcspNumber in AcspMembersService
- Add new query in AcspMembersRepository for fetching active ACSP member
- Create comprehensive test suite for isActiveMember endpoint in UserAcspMembershipInternalTest
- Tests cover various scenarios including unauthorized access, inactive ACSP, non-existent user, and active/inactive membership
- Reorganize existing tests into nested classes for better structure
https://companieshouse.atlassian.net/browse/IDVA6-1212
__An exhaustive list of peer review checks can be read [here](https://github.com/companieshouse/styleguides/blob/master/java_review.md#developer-actions-pri …
> IDVA6-1212: Implement isActiveMember endpoint and tests

- pom.xml
Updated pom.xml to use latest sonar.
IDVA6-1306
> Updated pom.xml to use latest sonar

- pom.xml
- src/main/java/uk/gov/companieshouse/acsp/manage/users/configuration/InterceptorConfig.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipController.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersService.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/common/TestDataManager.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/UserAcspMembershipControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembersRepositoryIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembersServiceIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembershipListMapperTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembershipMapperTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembershipsListMapperTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersServiceTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/utils/MapperUtilTest.java
> Idva6 1325 get membership endpoint

- src/main/java/uk/gov/companieshouse/acsp/manage/users/configuration/InterceptorConfig.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipsController.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/implementations/AcspMembershipsController.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/repositories/AcspMembersRepository.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/AcspDataService.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersService.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/utils/PaginationValidatorUtil.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembersRepositoryIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembersServiceIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipsControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersServiceTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/utils/PaginationValidatorUtilTest.java
Key Changes:
- Implemented GET /acsps/{acsp_number}/memberships endpoint
- Added AcspMembershipsController with filtering and pagination
- Enhanced AcspMembersRepository and AcspMembersService for efficient querying
- Created PaginationValidatorUtil for standardizing pagination
- Added integration tests covering new functionality
- https://companieshouse.atlassian.net/browse/IDVA6-1313
> IDVA6-1313: ACSP manage users api to fetch acsp memberships

- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipsController.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersService.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/utils/PaginationValidatorUtil.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/configuration/ApiClientConfigTest.java
Purpose was for getting [Sonar](https://code-analysis.platform.aws.chdev.org/dashboard?id=uk.gov.companieshouse%3Aacsp-manage-users-api) back up to scratch, this includes removing code smells/bugs.  Please note the test coverage will be above 80% after https://github.com/companieshouse/acsp-manage-users-api/pull/36 is merged, which is why I haven't targeted it in the pull request.
- Remove duplicate imports in AcspMembersService
- Use 'var' for local variables in AcspMembershipsController
- Make ApiClientConfigTest class package-private
- Add private constructor to PaginationValidatorUtil
- Fix typos and improve code style
- https://companieshouse.atlassian.net/browse/IDVA6-1361
__An exhaustive list of peer …
> IDVA6-1361: Refactor and clean up code across multiple files

- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipController.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/interceptor/AuthorizationAndInternalUserInterceptors.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/repositories/AcspMembersRepository.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersService.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/utils/RequestContextUtil.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembersRepositoryIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembersServiceIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersServiceTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/utils/RequestContextUtilTest.java
Added PATCH endpoint. Fixed issue in interceptor. 
IDVA6-1326
> Idva6 1326 patch endpoint

- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipsController.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/repositories/AcspMembersRepository.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersService.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipsControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembersRepositoryIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembersServiceIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipsControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersServiceTest.java
- Implement POST /acsps/{acspNumber}/memberships/lookup endpoint
- Add fetchAcspMemberships method to AcspMembersService
- Create new repository methods for fetching memberships by user ID and ACSP number
- Add integration tests for new functionality
- Update existing tests to accommodate changes
- https://companieshouse.atlassian.net/browse/IDVA6-1324
> IDVA6-1324: ACSP manage users api to lookup acsp memberships

- terraform/groups/ecs-service/locals.tf
The paths in Terraform hadn't been updated, so we can't hit the endpoints in Phoenix1.
IDVA6-1365
> Fixed paths

- terraform/groups/ecs-service/locals.tf
Updated load balancer paths
IDVA6-1365
> Updated load balancer paths

- suppress.xml
Added suppression file.
IDVA6-1365
> Added suppress.xml

- terraform/groups/ecs-service/locals.tf
> Updated lb_listener_paths

- pom.xml
- src/test/java/uk/gov/companieshouse/acsp/manage/users/common/TestDataManager.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembershipListMapperTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembershipMapperTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembershipsListMapperTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/utils/MapperUtilTest.java
- Update pom for AcspStatus changes
- Fix existing tests to use "active" instead of "live"
https://companieshouse.atlassian.net/browse/IDVA6-1382
> IDVA6-1382: Update pom for AcspStatus changes

- src/main/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembershipCollectionMappers.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/AcspDataService.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/UsersService.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembershipCollectionMappersTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/service/AcspDataServiceTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/service/UsersServiceTest.java
Added multi-threading to the mappers, so that they will run more efficiently.
IDVA6-940
> Added multi-threading to mapper.

- src/main/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembershipCollectionMappers.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersService.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembersServiceIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembershipCollectionMappersTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersServiceTest.java
Review feedback was to have the collections mapper extend the base mapper, instead of dependency injecting the base mapper. Implemented the review feedback
IDVA6-940
> Implemented review feedback

- pom.xml
- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipsController.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersService.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipsControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipsControllerIntegrationTest.java
Fixed a couple of bugs. Restructured the code to improve efficiency, and to enhance maintainability. 
IDVA6-1394
> Refactoring. Bug Fixes. Efficiency Improvements.

- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembersRepositoryIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembersServiceIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipsControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/UserAcspMembershipControllerIntegrationTest.java
mongodb upgrade test for test containers
> add mongosh dependency

- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembersRepositoryIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembersServiceIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipsControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/UserAcspMembershipControllerIntegrationTest.java
> rollback mongosh dependency

- pom.xml
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembersRepositoryIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembersServiceIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipsControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/UserAcspMembershipControllerIntegrationTest.java
Swapped TestContainers for Flapdoodle
IDVA6-1411
> Swapped TestContainers for Flapdoodle.

- src/test/resources/application.properties
> change mongo flapdoodle version

- README.md
Created a README File
IDVA6-1398
> Created README file.

- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipsController.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/UserAcspMembershipController.java
Removed some redundant logging, and standardised "Acsp" in logs.
IDVA6-1401
> Removed some redundant logging, and standardised "Acsp" in logs.

- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersService.java
> Changed ACSP to Acsp

- pom.xml
Updated kafka-clients version to the latest version
IDVA6-1484
> Updated kafka-clients version

- src/test/java/uk/gov/companieshouse/acsp/manage/users/common/ParsingUtils.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipsControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/UserAcspMembershipControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipsControllerIntegrationTest.java
Refactored most of the controller tests to improve code quality.
IDVA6-1514
> Refactored tests

- src/test/java/uk/gov/companieshouse/acsp/manage/users/common/ComparisonUtils.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/common/Preprocessors/Preprocessor.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/common/Preprocessors/ReduceTimeStampResolutionPreprocessor.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/common/TestDataManager.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembersServiceIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/UserAcspMembershipControllerIntegrationTest.java
Refactored some more of the tests
IDVA6-1514
> Refactored some more tests

- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/ControllerAdvice.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembershipCollectionMappers.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembershipMapper.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/AcspDataDao.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/AcspMembersDao.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/utils/StaticPropertyUtil.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/ControllerAdviceTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipsControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembershipMapperTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/rest/AccountsUserEndpointTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/service/UsersServiceTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/utils/RequestContextUtilTest.java
> Fixed sonar issues

- pom.xml
Updated spring version
IDVA6-1589
> IDVA6-1589: Updated spring version

- src/test/java/uk/gov/companieshouse/acsp/manage/users/common/ComparisonUtils.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembersRepositoryIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/interceptor/AuthorizationAndInternalUserInterceptorsTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/interceptor/AuthorizationInterceptorTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembershipCollectionMappersTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembershipMapperTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/rest/AccountsUserEndpointTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/rest/AcspProfileEndpointTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersServiceTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/service/UsersServiceTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/utils/PaginationValidatorUtilTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/utils/RequestContextUtilTest.java
Finished refactoring the remaining tests
IDVA6-1514
> IDVA6-1514: Third and final PR for refactoring acsp-manage-users-api tests

- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipsControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/model/email/YouHaveBeenAddedToAcspEmailDataTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/service/EmailServiceTest.java
Fixed some sonar issues
IDVA6-1457
> IDVA6-1457: Fixed sonar issues

- suppress.xml
> IDVA6-1635: Added suppressions

- terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
> Adding Staging profile

- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipController.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipControllerTest.java
Granted owners privilege to change other user's roles to owner.
IDVA6-1652
> IDVA6-1652: Granted owners privilege to change other user's roles to owner.

- suppress.xml
avro-1.11.3 is a part of email-producer-java. Suppressed.
IDVA6-1667
> IDVA6-1667: avro-1.11.3 is a part of email-producer-java. Suppressed.

- pom.xml
- src/main/java/uk/gov/companieshouse/acsp/manage/users/utils/RequestContextUtil.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/common/TestDataManager.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/interceptor/SessionValidityInterceptorTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/utils/RequestContextUtilTest.java
Changed acsp_id to acsp_number
IDVA6-1601
> IDVA6-1601: Changed acsp_id to acsp_number

- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipController.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/MessageType.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/email/YourRoleAtAcspHasChangedEmailData.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/email/YourRoleAtAcspHasChangedToAdminEmailData.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/email/YourRoleAtAcspHasChangedToOwnerEmailData.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/email/YourRoleAtAcspHasChangedToStandardEmailData.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/EmailService.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/ControllerAdviceTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/model/email/YourRoleAtAcspHasChangedEmailDataTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/model/email/YourRoleAtAcspHasChangedToAdminEmailDataTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/model/email/YourRoleAtAcspHasChangedToOwnerEmailDataTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/model/email/YourRoleAtAcspHasChangedToStandardEmailDataTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/service/EmailServiceTest.java
Added the edited role notification
IDVA6-1613
> IDVA6-1613: Added the edited role notification

- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipsController.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/MessageType.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/email/ConfirmYouAreAMemberEmailData.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/email/ConfirmYouAreAStandardMemberEmailData.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/email/ConfirmYouAreAnAdminMemberEmailData.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/email/ConfirmYouAreAnOwnerMemberEmailData.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/EmailService.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipsControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipsControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/model/email/ConfirmYouAreAMemberEmailDataTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/model/email/ConfirmYouAreAStandardMemberEmailDataTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/model/email/ConfirmYouAreAnAdminMemberEmailDataTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/model/email/ConfirmYouAreAnOwnerMemberEmailDataTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/service/EmailServiceTest.java
Replaced YouHaveBeenAddedToAcspEmail with ConfirmYouAreAStandardMember, ConfirmedYouAreAnAdminMember, and ConfirmYouAreAnOwnerMember.
IDVA6-1781 and IDVA6-1786
> IDVA6-1781 and IDVA6-1786: Replaced outdated email template

- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/email/ConfirmYouAreAMemberEmailData.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/email/ConfirmYouAreAStandardMemberEmailData.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/email/ConfirmYouAreAnAdminMemberEmailData.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/email/ConfirmYouAreAnOwnerMemberEmailData.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/email/YourRoleAtAcspHasChangedEmailData.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/email/YourRoleAtAcspHasChangedToAdminEmailData.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/email/YourRoleAtAcspHasChangedToOwnerEmailData.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/email/YourRoleAtAcspHasChangedToStandardEmailData.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/EmailService.java
- src/main/resources/application.properties
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipsControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/model/email/ConfirmYouAreAMemberEmailDataTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/model/email/ConfirmYouAreAStandardMemberEmailDataTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/model/email/ConfirmYouAreAnAdminMemberEmailDataTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/model/email/ConfirmYouAreAnOwnerMemberEmailDataTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/model/email/YourRoleAtAcspHasChangedEmailDataTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/model/email/YourRoleAtAcspHasChangedToAdminEmailDataTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/model/email/YourRoleAtAcspHasChangedToOwnerEmailDataTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/model/email/YourRoleAtAcspHasChangedToStandardEmailDataTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/service/EmailServiceTest.java
- src/test/resources/application.properties
Added signin.url to emails
IDVA6-1797
> IDVA6-1797: Added signin.url to emails

- pom.xml
> IDVA6-1924: Updated parent pom

- pom.xml
- suppress.xml
Upgraded Spring to the latest version, and addressed security failures.
IDVA6-1925
> IDVA6-1925: Upgraded spring

- pom.xml
- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipController.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipsController.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/UserAcspMembershipController.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/interceptor/AcspDataRetrievalPermissionInterceptor.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/interceptor/AuthorizationAndInternalUserInterceptors.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/interceptor/SessionValidityInterceptor.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/email/BaseEmailData.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/email/ConfirmYouAreAStandardMemberEmailData.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/email/ConfirmYouAreAnAdminMemberEmailData.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/email/ConfirmYouAreAnOwnerMemberEmailData.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/email/YourRoleAtAcspHasChangedToAdminEmailData.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/email/YourRoleAtAcspHasChangedToOwnerEmailData.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/email/YourRoleAtAcspHasChangedToStandardEmailData.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersService.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/AcspProfileService.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/EmailService.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/UsersService.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/utils/PaginationValidatorUtil.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/utils/RequestContextUtil.java
Added new logging and updated existing logging.
IDVA6-1953
> IDVA6-1953: Added new logging and updated existing logging.

- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipController.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipControllerTest.java
Updated PATCH endpoint to enable API Key requests to remove memberships for ceased ACSPs.
IDVA6-1986
> IDVA6-1986: Updated PATCH endpoint to enable API Key requests to remove memberships for ceased ACSPs.

- terraform/groups/ecs-service/main.tf
> update ecs modules

- pom.xml
Updated email regex.
IDVA6-2022
> IDVA6-2022: Updated email regex.

- pom.xml
- suppress.xml
Fix security failures
IDVA6-2077
> IDVA6-2077: Fix security failures

- src/main/java/uk/gov/companieshouse/acsp/manage/users/configuration/InterceptorConfig.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/interceptor/AcspDataRetrievalPermissionInterceptor.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/interceptor/AdminPermissionsInterceptor.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/interceptor/SessionValidityInterceptor.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipsControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/interceptor/AcspDataRetrievalPermissionInterceptorTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/interceptor/AdminPermissionsInterceptorTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/interceptor/SessionValidityInterceptorTest.java
Updated `getMembersForAcsp` endpoint to support requests from admin users with `/admin/acsp/search` permission.
IDVA6-2126
> IDVA6-2126: Updated getMembersForAcsp endpoint to support requests from admin users with /admin/acsp/search permission.

- terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
> Removing Autoscaling for performance testing

- terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
> Reinstating the Auto-scaling

- src/main/java/uk/gov/companieshouse/acsp/manage/users/configuration/WebSecurityConfig.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/filter/UserAuthenticationFilter.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/Constants.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/utils/RequestUtil.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/UserAcspMembershipControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/utils/RequestUtilTest.java
Relaxed constraints on GEt /user endpoint.
IDVA6-2207
> IDVA6-2207: Bug fix. GET /user endpoint needed to be relaxed

- Makefile
- pom.xml
> IDVA6-2214: Upgrading sonar

- pom.xml
- suppress.xml
Fixed security issues
IDVA6-2295
> IDVA6-2295: Fixed security issues

- src/main/resources/application.properties
- src/test/resources/application.properties
Updated signin.url value
IDVA6-2376
> IDVA6-2376: Updated signin.url value

- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/context/RequestContext.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersService.java
> Bug fix - ThreadLocal was becoming prematurely empty.

- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipsController.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/utils/ExceptionUtil.java
Bug fix - was logging errors when they had not occurred
SIV-173
> SIV-173: Bug fix - was logging errors when they had not occurred

- pom.xml
- src/main/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembershipCollectionMappers.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembershipMapper.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/AcspMembersDao.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/UsersService.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/common/TestDataManager.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipsControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipsControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembershipCollectionMappersTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembershipMapperTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/service/UsersServiceTest.java
> SIV-198: Skeleton

- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipsController.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/repositories/AcspMembersRepository.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersService.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/common/TestDataManager.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipsControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembersRepositoryIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembersServiceIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipsControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersServiceTest.java
Implemented invitations functionality in POST endpoint, excluding notification.
SIV-200
> SIV-200: Implemented invitations functionality in POST endpoint, excluding notification.

- src/main/java/uk/gov/companieshouse/acsp/manage/users/configuration/WebSecurityConfig.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipController.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersService.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/utils/UserUtil.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembersServiceIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersServiceTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/utils/UserUtilTest.java
Added invitations functionality to PATCH
SIV-201
> SIV-201: Added invitations functionality to PATCH

- pom.xml
- src/main/java/uk/gov/companieshouse/acsp/manage/users/configuration/WebSecurityConfig.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipController.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipsController.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/filter/UserAuthenticationFilter.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersService.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipsControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/ControllerAdviceTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/UserAcspMembershipControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/filter/UserAuthenticationFilterTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembersServiceIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersServiceTest.java
- src/test/resources/application.properties
Updated roles and permissions logic for pending users. Also implemented review comments for the main-invitations branch.
SIV-236
> SIV-236: Updated roles and permissions logic for pending users.

- pom.xml
- src/main/java/uk/gov/companieshouse/acsp/manage/users/configuration/WebSecurityConfig.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipController.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipsController.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/controller/UserAcspMembershipController.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/filter/UserAuthenticationFilter.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembershipCollectionMappers.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembershipMapper.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/model/AcspMembersDao.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/repositories/AcspMembersRepository.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersService.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/service/UsersService.java
- src/main/java/uk/gov/companieshouse/acsp/manage/users/utils/UserUtil.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/common/TestDataManager.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/AcspMembershipsControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/ControllerAdviceTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/controller/UserAcspMembershipControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/filter/UserAuthenticationFilterTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembersRepositoryIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembersServiceIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipControllerTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/AcspMembershipsControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/integration/UserAcspMembershipControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembershipCollectionMappersTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/mapper/AcspMembershipMapperTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/service/AcspMembersServiceTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/service/UsersServiceTest.java
- src/test/java/uk/gov/companieshouse/acsp/manage/users/utils/UserUtilTest.java
- src/test/resources/application.properties
Invitations functionality
SIV-195
> SIV-195 - Main Invitations

- Makefile
- pom.xml
- suppress.xml
Upgraded dependency check and fixed security vulnerabilities.
Created these two commands to test the dependency check:
`docker pull 416670754337.dkr.ecr.eu-west-2.amazonaws.com/dependency-check-runner
`
`docker run --rm -e DEPENDENCY_CHECK_SUPPRESSIONS_HOME=/opt -e REPO_CONFIG_SUPPRESS_FILE_LIST=suppress.xml -v "$(pwd)":/app -v "$(pwd)/suppress.xml":/opt/suppress.xml -w /app 416670754337.dkr.ecr.eu-west-2.amazonaws.com/dependency-check-runner`
Outstanding: these two commands will need to be added to the pipeline. We also need to change the order of tasks so `dependency-check` runs before `sonar`.
SIV-373
__An exhaustive list of peer review checks can be read …
> SIV-373: Upgraded dependency check

- pom.xml
fixing security vulnerabilities
SIV-576
> SIV-576: fixing security vulnerabilities

- pom.xml
CVE | Dependency | Old Version | New Version
-- | -- | -- | --
CVE-2025-41249 | org.springframework:spring-core (via Spring Framework) | 6.2.10 | 6.2.11
CVE-2025-41248 | org.springframework.security:spring-security-core (via Spring Security) | 6.5.3 | 6.5.4
Please note that it was necessary to explicitly manage several Spring dependencies rather than relying solely on spring-boot-dependencies. This is because the current Spring Boot release does not yet align with the patched versions of Spring Framework and Spring Security, so we had to override them manually to remove the vulnerabilities.
[SIV-766: Fix Vulnerabilities in ascp-manage-users-api](https://companieshouse.atlassian.net/browse/SIV-766)
__An exhaustive …
> SIV-766: Fix Vulnerabilities in ascp-manage-users-api

- README.md
> remove references to tilt
